config/routes.rb
SpancMan1::Application.routes.draw do

  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  resources :dossiers do
    resources :immeubles, :users, :installations, :terrains, :audits, :entretiens, :comptabs
  end

  resources :listes
  resources :rdvs
  resources :contacts

  resources :epandages
  resources :traitements
  resources :pretraitements
  resources :regards
  match 'user/edit' => 'users#edit', :as => :edit_current_user
  match 'signup' => 'users#new', :as => :signup
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'login' => 'sessions#new', :as => :login
  resource :sessions
  resources :users

  root :to => 'sessions#new'

end

app/models/dossier.rb
class Dossier < ActiveRecord::Base
  acts_as_audited
  has_associated_audits
  acts_as_taggable

  #validations
  validates :reference, :presence => true, :uniqueness => true, :length => { :maximum => 100 }

  #associations

  has_many :listes
  has_many :users, :as => :userable
  has_many :immeubles, :dependent => :destroy
  #accepts_nested_attributes_for :immeubles, :allow_destroy => true
  has_many :installations, :dependent => :destroy
  accepts_nested_attributes_for :installations, :allow_destroy => true
  has_many :terrains, :dependent => :destroy
  accepts_nested_attributes_for :terrains, :allow_destroy => true
  has_many :entretiens, :dependent => :destroy
  accepts_nested_attributes_for :entretiens, :allow_destroy => true
  has_many :comptabs, :dependent => :destroy
  accepts_nested_attributes_for :comptabs, :allow_destroy => true

end

app/controllers/dossiers_controller.rb
class DossiersController < ApplicationController
  set_tab :dossier

  def tag_cloud
      @tags = Post.tag_counts_on(:tags)
  end

  def index
    @search = Dossier.search(params[:search])
    @dossiers = @search.all
  end

  def show
    @dossier = Dossier.find(params[:id])

    @proprio = @dossier.users.where(:destinataire => true & {:immeuble => {:dossier_id => params[:id]}}).joins(:immeuble)
  end

  def new
    @dossier = Dossier.new
  end

  def create

    @dossier = Dossier.new(params[:dossier])
    letcaptital(@dossier.reference)
    if @dossier.save
      redirect_to new_dossier_immeuble_path(@dossier), :notice => "Dossier créé avec brio"
    else
      render :action => 'new'
    end
  end

  def edit
    @dossier = Dossier.find(params[:id])
  end

  def update
    @dossier = Dossier.find(params[:id])
    if @dossier.update_attributes(params[:dossier])
      redirect_to @dossier, :notice  => "Dossier magnifiquement mis à jour"
    else
      render :action => 'edit'
    end
  end

  def destroy
    @dossier = Dossier.find(params[:id])
    @dossier.destroy
    redirect_to dossiers_url, :notice => "Dossier détruit définitivement."
  end


  def letcaptital(objet)
    return objet.upcase
  end
end

app/helpers/dossiers_helper.rb
module DossiersHelper
include ActsAsTaggableOn::TagsHelper
end

app/views/dossiers/_dossier.html.erb
<div class="container outline">

<table id="classic">
  <tbody>
    <tr><td>Nombre d'immeubles dans le dossier :</td><td><%= @dossier.immeubles.count %></td></tr>
    <tr><td>adresse imm. principal :</td><td>

      <% @dossier.immeubles.principal.each do |immeu|%>
        <%= immeu.numero_rue %> <%= immeu.adresse %><br/>
        <%= immeu.code_postal%> <%= affiche_liste(immeu.commune,'') %><br/>

    </td></tr>

    <tr><td>Propriétaire(s) :</td><td>
    <div class="large">
      <% immeu.users.proprio_destinat.each do |proprio|%>
        <%= proprio.username %>
      <%end%><br/>
    </div></td></tr>
      <%end%>

    <tr><td>secteur :</td>
    <td><%= affiche_liste(@dossier.secteur,'') %>
    </td></tr>
  </tbody>
</table>
      <p>
      </p>
      commentaires :
      <div class="box">
        <%= simple_format @dossier.commentaire %>
      </div>
<span class="small quiet right"> créé le <%= l(@dossier.created_at.to_date) %> - modifié le <%= l(@dossier.updated_at.to_date) %></span>
</div>
<hr/>

app/views/dossiers/_form.html.erb
<div id="margin">

<div class="two column">
<%= simple_form_for @dossier do |f|%>
  <%= f.error_messages %>
    <fieldset>
    <legend>dossier</legend>
      <%= f.input :etat, :collection => Liste.etat.all(:order => 'nom'), :label_method => 'nom' %>
      <%= f.input :reference, :hint => 'obligatoire' %>
      <%= f.input :archivage %>
      <%= f.input :secteur, :collection => Liste.secteur.all(:order => 'nom'), :label_method => 'nom', :as => :radio %><br/><br/>
      <fieldset>
      <legend>coordonnées</legend>
      <%= f.input :coordx, :label => 'x ', :input_html => { :size => '8'}%>
      <%= f.input :coordy, :label => 'y ', :input_html => { :size => '8'}%>
      </fieldset>
    </fieldset>
</div>
<div class="two column">
  <fieldset>
    <legend>commentaire</legend>
    <%= f.input :tag_list, :label =>'mots clés' %>
    <%= f.input :commentaire, :input_html => { :rows => 3, :cols => 60 }%>
  </fieldset>
  <%= f.button :submit%>
</div>
<%end%>
</div>

app/views/dossiers/_histo.html.erb
<h3>Historique</h3>
<!-- TODO ranger dans l'ordre inverse des versions-->
<% @audits.each do |r|%>
<div class="section">
<div class="two column">
<span class="quiet"> <%= r.version %></span>-
<%= image_tag(r.action.to_s+".png", :class =>"class") %> <%= l(r.created_at) %>

</div>

<div class="one column">
  <div class="container">
    <%= User.find_by_id(r.user_id).username %> <!-- nom du modificateur -->
  </div>

</div>
<div class="four column">
    <% if r.action=="create"%>
    <div class="fond">Création : <%= r.auditable_type %></div>
    <% elsif r.action=="destroy" %>
    <div class="fond">Effacement : <%= r.auditable_type %></div>
    <% else %>
    <% r.audited_changes.each do |chang|%>
      <div class="fond">dans <%= r.auditable_type %> : <%= chang.first %></div>
        <% @diff = Differ.diff_by_word(chang[1][1], chang[1][0]) %>
        <%# simple_format @diff.format_as(:html), :class => 'small' %>
      <%end%>
   <%end %>
   <div class="small quiet "> <!-- TODO mettre en place les commentaires -->
  <% if r.comment%>
    <%= r.comment %>
  <% else %>
    pas de commentaires
  <%end%>
  </div>
</div>
</div>
<%end %>

app/views/dossiers/edit.html.erb
Modifier le dossier
<% title @dossier.reference %>
<%= render ('layouts/navigation') %>
<p><%= link_to "retour dossier", @dossier, :class =>'retour' %></p>
<%= render 'form' %>
<p><%= link_to "retour dossier", @dossier, :class =>'retour' %></p>

app/views/dossiers/index.html.erb
<% title "LISTE DES DOSSIERS" %>
<h1>LISTES DES DOSSIERS</h1>

<div class="twelve_column section">
    <!--
    recherche
    -->
  <div class="nine column">
        <tr>
        <%= simple_form_for @search do |f| %>
        <td><span class="large"> <%= f.input :reference_contains, :as => :search, :label => false %></span></td>
        <td><%# f.input :dossiers_communes_equals, :label => false, :collection => Liste.commune , :label_method => 'nom' %></td>
        <td><%= f.input :secteur_contains, :label => false, :collection => Liste.secteur, :label_method => 'nom' %></td>
        <td></td>
        <td><%= f.button :submit %><%= link_to 'RAZ', root_path, :class => "destroy_link" %></td>
        <td></td>
        <% end %>
      </tr>

  <table id="classic">
  <caption>nombre dossiers (trouvé/total) : <%= @dossiers.count %> / <%= Dossier.all.count %></caption>

    <thead>
      <tr>
        <th><%= sort_link(@search, 'reference', 'Réf.SPANC') %></th>
        <th><%= sort_link(@search, 'commune','commune') %></th>
        <th><%= sort_link(@search, 'secteur','secteur') %></th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>


    <% @dossiers.each do |dossier|%>
      <%= content_tag_for(:tr,dossier) do %>
        <td><%= link_to(dossier.reference.upcase, dossier)%></td>

        <td><% dossier.immeubles.principal.each do |dodo|%>
            <%= affiche_liste(dodo.commune,'') %>
        <%end %></td>
        <td><%= affiche_liste(dossier.secteur,'') %></td>
        <td><% dossier.users.each do |proprio|  %>
              <%= proprio.username if proprio.username%><br/>
           <%end%></td>
        <td><%= affiche_liste(dossier.etat,'') %></td>
        <td></td>
      <% end %>
    <% end %>
    </tbody>
  </table>



  </div>



  <div class="three column">
    <div class="container box"> <%= link_to 'creer un dossier', new_dossier_path, :class => 'link ajout' %><br/>
    </div>
    <div class="container box">
        <p>Gérer :</p>
      <%= link_to image_tag("icons/ui-combo-box.png", :alt => "termes", :title => "termes") + ' Listes des termes', listes_path%>
    </div>
    <div class="container">
      <p>cliquer sur le numero de dossier pour le voir</p>
    </div>


  </div>

</div>

app/views/dossiers/new.html.erb
<% title "Nouveau Dossier"%>
<h1>Nouveau Dossier</h1>
<p><%= link_to "retour accueil", dossiers_path, :class =>'retour' %></p>
<%= render 'form' %>
<p><%= link_to "retour accueil", dossiers_path, :class =>'retour' %></p>

app/views/dossiers/show.html.erb
<% title @dossier.reference %>
<%= render ('layouts/navigation') %>

<div class="twelve_column section">
  <div class="seven column border">
    <%= render @dossier %>
  </div>
  <div class="three column border">
    <div class="container">
    <%=  image_tag("images.jpg", :alt => "carte", :class =>"liqimg top")%>
    <p>truc sous la photo</p>
    </div>
  </div>
  <div class="two column">
    <div class="container box">

<%= link_to "Modifier", edit_dossier_path(@dossier), :class =>'edit_link'%><br/>
<%= link_to "Détruire", @dossier, :confirm => 'certain?', :method => :delete, :class => 'destroy_link' %>

    </div>
  </div>
</div>