config/routes.rb
SpancMan1::Application.routes.draw do

  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  resources :dossiers do
    resources :immeubles, :users, :installations, :terrains, :audits, :entretiens, :comptabs
  end

  resources :listes
  resources :rdvs
  resources :contacts

  resources :epandages
  resources :traitements
  resources :pretraitements
  resources :regards
  match 'user/edit' => 'users#edit', :as => :edit_current_user
  match 'signup' => 'users#new', :as => :signup
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'login' => 'sessions#new', :as => :login
  resource :sessions
  resources :users

  root :to => 'sessions#new'

end

app/models/installation.rb
class Installation < ActiveRecord::Base
  #attr_accessible :dossier_id, :type_instal
  acts_as_audited :associated_with => :dossier

  belongs_to :dossier
  has_many :pretraitements
  accepts_nested_attributes_for :pretraitements, :allow_destroy => true
  has_many :traitements
  accepts_nested_attributes_for :traitements, :allow_destroy => true
  has_many :epandages
  accepts_nested_attributes_for :epandages, :allow_destroy =>true

end

app/controllers/installations_controller.rb
class InstallationsController < ApplicationController
  before_filter :load_dossier
  set_tab :installation

  def index
    @installations = @dossier.installations.all
    @liste = Liste.type_install
  end

  def show
    @installation = @dossier.installations.find(params[:id])
    @list_type = Liste.find_by_id(@installation.id)
  end

  def new
    @installation = @dossier.installations.new
    @immeubles = @dossier.immeubles


  end

  def create
    @installation = @dossier.installations.new(params[:installation])
    if @installation.save
      redirect_to dossier_installations_path, :notice => "Installation courageusement mise en place"
    else
      render :action => 'new'
    end
  end

  def edit
    @installation = @dossier.installations.find(params[:id])
  end

  def update
    @installation = @dossier.installations.find(params[:id])

    if @installation.update_attributes(params[:installation])
      redirect_to dossier_installations_path, :notice  => "installation mise à jour"
    else
      render :action => 'edit'
    end
  end

  def destroy
    @installation = @dossier.installations.find(params[:id])
    @installation.destroy
    redirect_to dossier_installations_path, :notice => "installation détruite !"
  end

  private
  def load_dossier
    @dossier = Dossier.find(params[:dossier_id])
  end

end

app/helpers/installations_helper.rb
module InstallationsHelper
end

app/views/installations/_form.html.erb
<p><div class="large"><%= link_to "Retour", dossier_installations_path, :class => 'retour' %></div></p>

<div class="twelve_column section">

<div class="ten column border">
<div class="outline">


<%= simple_form_for ([@dossier,@installation]) do |f| %>

<fieldset>
<legend> Installation </legend>
<%= f.input :type_instal, :collection => Liste.type_install.all(:order => 'nom'), :label_method => 'nom', :as => :select, :label => "Type d'installation"  %>
<%= f.input :date, :as => :string %>

<div class="cache">
  <div id="DropZone"></div>
</div>

</fieldset>
    <%= f.simple_fields_for :pretraitements do |builder| %>
        <%= render "pretraitements/form", :f => builder %>
      <% end %>
    <%= f.simple_fields_for :traitements do |builder| %>
        <%= render "traitements/form", :f => builder %>
    <% end %>
        <%= f.simple_fields_for :epandages do |builder| %>
        <%= render "epandages/form", :f => builder %>
    <% end %>
    <p><%= submit_or_cancel(f)%></p>
</div>



</div>
<div class="two column">
  <div class="container box">
  <p>Ajouter un :</p>
        <%= link_add_in_drop ('pretraitement', f, :pretraitements) %><br/>
  </div><!--fin container box-->
  <div class="container box">
    Traitements :<br/>
    <%= link_add_in_drop ('epandage', f, :epandages) %>
  </div>

<div class="container box">
  <a href="#" id="voir_origine" class="">Voir origines des eaux</a>

  <div id="listorigine"> <!-- liste des pièces des immeubles genere_EU = true -->
    <% @dossier.immeubles.each do |immeuble|%>
      <h4><a href="#">Imm. n° <%= immeuble.number %></a></h4> <!--liste les immeubles -->
      <div>
        <% immeuble.liste_pieces.genere.each do |piece|%>
          <li>Imm. n°<%= immeuble.number %> : <%= Liste.find_by_id(piece.piece).nom %> </li> <!-- liste les pièces-->
        <%end%>
    </div>
    <%end%>
      <h4><a href="#"> Autres </a></h4>
      <ul>
      <li>Toutes eaux </li>
      <li>Toutes eaux ménagères </li>
      <li>Toutes eaux vannes </li>
      <li>Eaux pluviales</li>
      </ul>


  </div> <!-- fin id liste-->
</div> <!--fin container box-->

</div> <!-- fin two col -->
<% end %> <!-- fin formulaire ici pour lien dans sidebar -->
</div> <!--fin twelve-->

app/views/installations/_installation.html.erb
<div class="outline">

<table id="classic">
  <tr>
    <th>Type Instal</th>
    <th>date de référence</th>
    <th>pretraitements</th>
    <th>créée le</th>

  </tr>
  <% @installations.each do |installation| %>
    <tr>
      <td><% li = @liste.find_by_id(installation.type_instal) %><%# li.nom if li.nom %>
      </td>
      <td><%= installation.date %></td>
      <td><% installation.pretraitements.each do |pret|%>
            <%= pret.origine %>
            <%= pret.vue %>
            <% end %>
          </td>
      <td><%= installation.created_at %></td>
      <td>
      <%= link_to image_tag("icons/eye.png", :alt => "voir", :title => "voir"), [@dossier,installation] %> |
      <%= link_to image_tag("icons/pencil.png", :alt => "modifier", :title => "modifier"), edit_dossier_installation_path(@dossier,installation) %> |
      <%= link_to image_tag("icons/cross.png", :alt => "détruire", :title => "détruire"), [@dossier,installation] , :confirm => 'Are you sure?', :method => :delete %>
      </td>
    </tr>
  <% end %>
</table>
</div>

app/views/installations/edit.html.erb
<% title @dossier.reference %>
<div class="large">Modifier une installation </div>
<%= render ('layouts/navigation') %>

<%= render 'form' %>

app/views/installations/index.html.erb
<% title @dossier.reference %>
<%= render ('layouts/navigation') %>

<div class="twelve_column section">

<div class="ten column border">
<%= render 'installation' %>
</div>

<div class="two column">
  <div class="container box">
    <%= link_to "Ajouter une installation", new_dossier_installation_path(@dossier), :class => "ajout" %>
  </div>
</div>
</div>

app/views/installations/new.html.erb
<% title @dossier.reference %>
<div class="large">Créer une installation</div>
<%= render ('layouts/navigation') %>

<%= render 'form' %>

app/views/installations/show.html.erb
<% title "Installation" %>

<p>
  <strong>Dossier:</strong>
  <%= @installation.dossier_id %>
</p>
<p>
  <strong>Type Instal:</strong>
  <%= @installation.type_instal %>
</p>

<p>
  <%= link_to "Edit", edit_installation_path(@installation) %> |
  <%= link_to "Destroy", @installation, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", installations_path %>
</p>