config/routes.rb
SpancMan1::Application.routes.draw do

  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  resources :dossiers do
    resources :immeubles, :users, :installations, :terrains, :audits, :entretiens, :comptabs
  end

  resources :listes
  resources :rdvs
  resources :contacts

  resources :epandages
  resources :traitements
  resources :pretraitements
  resources :regards
  match 'user/edit' => 'users#edit', :as => :edit_current_user
  match 'signup' => 'users#new', :as => :signup
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'login' => 'sessions#new', :as => :login
  resource :sessions
  resources :users

  root :to => 'sessions#new'

end

app/models/rdv.rb
class Rdv < ActiveRecord::Base
  #attr_accessible :type_rdv, :debut_rdv, :fin_rdv, :controleur, :contact, :ref_dossier, :lieu, :rappel, :description
  has_event_calendar :start_at_field  => 'debut_rdv', :end_at_field => 'fin_rdv'
  belongs_to :calendrier
end

app/controllers/rdvs_controller.rb
class RdvsController < ApplicationController
  def index
    @rdvs = Rdv.all
  end

  def show
    @rdv = Rdv.find(params[:id])
  end

  def new
    @rdv = Rdv.new
  end

  def create
    @rdv = Rdv.new(params[:rdv])
    if @rdv.save
      redirect_to @rdv, :notice => "Successfully created rdv."
    else
      render :action => 'new'
    end
  end

  def edit
    @rdv = Rdv.find(params[:id])
  end

  def update
    @rdv = Rdv.find(params[:id])
    if @rdv.update_attributes(params[:rdv])
      redirect_to @rdv, :notice  => "Successfully updated rdv."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @rdv = Rdv.find(params[:id])
    @rdv.destroy
    redirect_to rdvs_url, :notice => "Successfully destroyed rdv."
  end

end

app/helpers/rdvs_helper.rb
module RdvsHelper
end

app/views/rdvs/_form.html.erb
<%= simple_form_for @rdv do |f|%>
  <%= f.input :type_rdv %>
  <%= f.input :debut_rdv %>
  <%= f.input :fin_rdv %>
  <%= f.input :controleur %>
  <%= f.input :contact %>
  <%= f.input :ref_dossier%>
  <%= f.input :lieu %>
  <%= f.input :rappel %>
  <%= f.input :description %>
  <%= f.button :submit%>
<%end%>

app/views/rdvs/_rdv.html.erb
<table id="classic">
  <thead>
  <tr>
    <th>Type</th>
    <th>Début</th>
    <th>Fin</th>
    <th>Controleur</th>
    <th>Contact</th>
    <th>Ref Dossier</th>
    <th>Lieu</th>
    <th>Description</th>
  </tr>
  </thead>
  <% for rdv in @rdvs %>
    <tr>
      <td></td>
      <td></td>
      <td><%= rdv.fin_rdv %></td>
      <td><%= rdv.controleur %></td>
      <td><%= rdv.contact %></td>
      <td><%= rdv.ref_dossier %></td>
      <td><%= rdv.lieu %></td>
      <td><%= rdv.description %></td>
      <td><%= link_to "Show", rdv %></td>
      <td><%= link_to "Edit", edit_rdv_path(rdv) %></td>
      <td><%= link_to "Destroy", rdv, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

app/views/rdvs/edit.html.erb
<% title "Edit Rdv" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @rdv %> |
  <%= link_to "View All", rdvs_path %>
</p>

app/views/rdvs/index.html.erb
<% title "Calendrier" %>

<h1>Calendrier</h1>
<%= link_to "retour calendrier", calendar_path, :class =>'retour' %><br/>


<div class="twelve_column section">
  <div class="ten column border">
    <%= render "rdv" %></div>
  <div class="two column">
    <div class="container box">
      <%= link_to "Nouveau RDV", new_rdv_path, :class => "create_link" %>
    </div>
    <div class="container box">
      voir aujourd'hui
      voir cette semaine
      voir tout
      entre le et le
    </div>
  </div>
</div><!-- fin 12 col -->

app/views/rdvs/new.html.erb
<% title "New Rdv" %>

<%= render 'form' %>

<p><%= link_to "Back to List", rdvs_path %></p>

app/views/rdvs/show.html.erb
<% title "Calendrier" %>

<h1>Rendez-vous</h1>
<%= link_to "retour calendrier", calendar_path, :class =>'retour' %><br/>


<%= affiche_liste(@rdv.type_rdv,'Type : ') %>
<p>
  <strong>Debut Rdv:</strong>
  <%= l(@rdv.debut_rdv) %>
</p>
<p>
  <strong>Fin Rdv:</strong>
  <%= l(@rdv.fin_rdv )%>
</p>
<p>
  <strong>Controleur:</strong>
  <%= @rdv.controleur %>
</p>
<p>
  <strong>Contact:</strong>
  <%= @rdv.contact %>
</p>
<p>
  <strong>Ref Dossier:</strong>
  <%= @rdv.ref_dossier %>
</p>
<p>
  <strong>Lieu:</strong>
  <%= @rdv.lieu %>
</p>
<p>
  <strong>Rappel:</strong>
  <%= @rdv.rappel %>
</p>
<p>
  <strong>Description:</strong>
  <%= @rdv.description %>
</p>

<p>
  <%= link_to "Edit", edit_rdv_path(@rdv) %> |
  <%= link_to "Destroy", @rdv, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", rdvs_path %>
</p>