config/routes.rb
SpancMan1::Application.routes.draw do

  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  resources :dossiers do
    resources :immeubles, :users, :installations, :terrains, :audits, :entretiens, :comptabs
  end

  resources :listes
  resources :rdvs
  resources :contacts

  resources :epandages
  resources :traitements
  resources :pretraitements
  resources :regards
  match 'user/edit' => 'users#edit', :as => :edit_current_user
  match 'signup' => 'users#new', :as => :signup
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'login' => 'sessions#new', :as => :login
  resource :sessions
  resources :users

  root :to => 'sessions#new'

end

app/models/epandage.rb
class Epandage < ActiveRecord::Base
  attr_accessible :nb_epandage, :long_epand, :largeur_epand, :profondeur, :epaisseur_graviers, :calibre_graviers, :entraxes, :installation_id, :type_renseignements, :saturation, :ok, :observations
  belongs_to :installation
  has_many :regards, :as => :regardable, :dependent => :destroy
  accepts_nested_attributes_for :regards, :allow_destroy => true
end

app/helpers/epandages_helper.rb
module EpandagesHelper
end

app/views/epandages/_form.html.erb
<div class="fields">
  <fieldset>
    <legend>Epandage</legend>
    <div class="left"><%= image_tag("tranchee.png", :size => "360x180",:alt => "epandage") %></div>
    <div class="one column"><%= f.input :type_renseignements %></div>
    <div class="one column"><%= f.input :nb_epandage, :collection =>1..8 %></div>
    <div class="one column">
    <%= f.input :long_epand, :label =>'longueur épandage' %></div>
    <div class="one column"><%= f.input :largeur_epand, :label=>'largeur tranchées' %></div>
    <%= f.input :profondeur %>
    <%= f.input :entraxes %>
    <%= f.input :epaisseur_graviers %>
    <%= f.input :calibre_graviers %>
    <%= f.input :saturation %>
    <%= f.input :ok %>
    <%= f.input :observations %>
  </div>
  <div class="clear">

  <%= f.simple_fields_for :regards do |builder| %>
    <%= render "regards/form", :f => builder %>
  <% end %>
  <p><%= link_to_add_fields("Ajouter un accès", f, :regards) %></p>
  </div>
  </fieldset>
</div>

app/views/epandages/edit.html.erb
<% title "Edit Epandage" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @epandage %> |
  <%= link_to "View All", epandages_path %>
</p>

app/views/epandages/index.html.erb
<% title "Epandages" %>

<table id="classic">
  <tr>
    <th>Nb Epandage</th>
    <th>Long Epand</th>
    <th>Largeur Epand</th>
    <th>Profondeur</th>
    <th>Epaisseur Graviers</th>
    <th>Calibre Graviers</th>
    <th>Entraxes</th>
    <th>Installation</th>
    <th>Type Renseignements</th>
    <th>Saturation</th>
    <th>Ok</th>
    <th>Observations</th>
  </tr>
  <% for epandage in @epandages %>
    <tr>
      <td><%= epandage.nb_epandage %></td>
      <td><%= epandage.long_epand %></td>
      <td><%= epandage.largeur_epand %></td>
      <td><%= epandage.profondeur %></td>
      <td><%= epandage.epaisseur_graviers %></td>
      <td><%= epandage.calibre_graviers %></td>
      <td><%= epandage.entraxes %></td>
      <td><%= epandage.installation_id %></td>
      <td><%= epandage.type_renseignements %></td>
      <td><%= epandage.saturation %></td>
      <td><%= epandage.ok %></td>
      <td><%= epandage.observations %></td>
      <td><%= link_to "Show", epandage %></td>
      <td><%= link_to "Edit", edit_epandage_path(epandage) %></td>
      <td><%= link_to "Destroy", epandage, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Epandage", new_epandage_path %></p>

app/views/epandages/new.html.erb
<% title "New Epandage" %>

<%= render 'form' %>

<p><%= link_to "Back to List", epandages_path %></p>

app/views/epandages/show.html.erb
<% title "Epandage" %>

<p>
  <strong>Nb Epandage:</strong>
  <%= @epandage.nb_epandage %>
</p>
<p>
  <strong>Long Epand:</strong>
  <%= @epandage.long_epand %>
</p>
<p>
  <strong>Largeur Epand:</strong>
  <%= @epandage.largeur_epand %>
</p>
<p>
  <strong>Profondeur:</strong>
  <%= @epandage.profondeur %>
</p>
<p>
  <strong>Epaisseur Graviers:</strong>
  <%= @epandage.epaisseur_graviers %>
</p>
<p>
  <strong>Calibre Graviers:</strong>
  <%= @epandage.calibre_graviers %>
</p>
<p>
  <strong>Entraxes:</strong>
  <%= @epandage.entraxes %>
</p>
<p>
  <strong>Installation:</strong>
  <%= @epandage.installation_id %>
</p>
<p>
  <strong>Type Renseignements:</strong>
  <%= @epandage.type_renseignements %>
</p>
<p>
  <strong>Saturation:</strong>
  <%= @epandage.saturation %>
</p>
<p>
  <strong>Ok:</strong>
  <%= @epandage.ok %>
</p>
<p>
  <strong>Observations:</strong>
  <%= @epandage.observations %>
</p>

<p>
  <%= link_to "Edit", edit_epandage_path(@epandage) %> |
  <%= link_to "Destroy", @epandage, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", epandages_path %>
</p>